### ISSUE TITLE
Monitoring workshop

### ISSUE THREAD

**Issue by tenstad** [Informasjonsforvaltning/fdk-infra#117]
- [x] scrape metrics from reference data path `/reference-data/actuator/prometheus`
- [x] alert when image has more than 10 critical vulnerabilities
- [x] alert when mail sender error occurs
- [x] create critical image vulnerability graph (see changes over time)
- [x] afterwork planning @LeneSundsbo

**Comment by KjerstiSteien** [comment]
@jeffreiffers Skal de resterende punktene her fikses, eller skal vi lukke saken?

**Comment by jeffreiffers** [comment]
Ja de bør fikses!
