### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by tenstad** [Informasjonsforvaltning/fdk-infra#35]
- [x] prometheus monitoring stack
  - [x] deploy
  - [x] custom configuration
  - [x] thanos
  - [x] alertmanager
  - [x] custom alerts
- [x] [grafana dashboards](https://github.com/Informasjonsforvaltning/fdk-grafana-dashboards)
  - [x] deployment pipeline
  - [x] kafka
  - [x] mqa
  - [x] http
  - [x] rabbit
  - [x] elasticsearch
  - [x] nginx
- [x] skjerm
  - [x] skjerm
  - [x] pc til skjerm

**Comment by valosnah** [comment]
![image](https://user-images.githubusercontent.com/8625716/185732546-caf6f3c7-4ab7-4b04-bbae-eefd558c5f4e.png)

Prometheus har fylt disken på 11 dager.

**Comment by tenstad** [comment]
> Prometheus har fylt disken på 11 dager.

Det høres jo nesten helt perfekt ut, retention er satt til 10 dager :sweat_smile: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=values&path=prometheus.prometheusSpec.retention

**Comment by tenstad** [comment]
Reduserer scrape intervall og bumper disken litt: https://github.com/Informasjonsforvaltning/fdk-infra/pull/54/files

**Comment by tenstad** [comment]
:cake:
